DROP TABLE IF EXISTS whats_next_users;

CREATE TABLE whats_next_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    display_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);